### ISSUE TITLE
URL Routing for news_feuser

### ISSUE THREAD

**Issue by typo3ua** [georgringer/news_feuser#8]
I wrote this...
```
routeEnhancers:
  NewsListUser:
    type: Extbase
    limitToPages:
      - 10
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '/page/{page}'
        _controller: 'News::list'
        _arguments:
          page: '@widget_0/currentPage'
      -
        routePath: '/user/{user_uid}'
        _controller: 'News::perUser'
        _arguments:
          user_uid: 'overwriteDemand/user'
    defaultController: 'News::list'
    defaults:
      page: '0'
    requirements:
      page: '\d+'
    aspects:
      page:
        type: StaticRangeMapper
        start: '1'
        end: '100'
      user_uid:
        type: PersistedAliasMapper
        tableName: 'tx_news_domain_model_news'
        routeFieldName: 'tx_newsfeuser_user'
```
...but I fail to get triple result. Maybe I do not understand something I need your help...
